### ISSUE TITLE
No support for Firefox, Safari, or mobile Chrome

### ISSUE THREAD

**Issue by gmac** [LaNsHoR/native-json-editor#1]
This is a really cool library, unfortunately it only really works in Chrome (desktop). The main blocker from being functional across browsers is the lack of a standard [ShadowRoot.getSelection](https://developer.mozilla.org/en-US/docs/Web/API/ShadowRoot#methods). This can be shimmed for Firefox, but not Safari.

Option for making it work across browsers is to eliminate the use of Shadow DOM until something standard exists. I've proven this theory with a local Vue component adaption that renders to the component DOM, at which time selections can be pulled consistently from the parent window.

**Comment by LaNsHoR** [comment]
Thanks! I'll investigate this week about how I could replace getSelection on ShadowRoot.

I have an older version which doesn't use shadow dom at all, that one I think should work in most browsers out there: https://github.com/LaNsHoR/json-text-editor/tree/c8be9f395618b8591766495967c03f6452068ffb (it's in a different repo, json-text-editor instead of native-json-text-editor).

PS: That old version doesn't work exactly in the same way, but it's similar (at least internally). In any case I hope to fix the issue in this version soon!

**Comment by LaNsHoR** [comment]
Pushed a new version that I tested on Firefox and Edge. It looks good so far :)

I'll perform some tests on Safari, Opera and some mobile versions on the popular browsers the upcoming week. I'll keep this open until then.
